### ISSUE TITLE
Improvement to WithStatusCode Assertion

### ISSUE THREAD

**Issue by foresightyj** [ivaylokenov/MyTested.WebApi#249]
*This is a suggestion, not a bug.* (BTW, is this a good way to suggest features? My solution is hacky and inelegant so I dare not to have a pull request.)

Currently, with the following code:

    .ShouldReturnHttpResponseMessage()
    .WithStatusCode(HttpStatusCode.OK)

In the case that the actual response is not OK, the unit test throws an exception like this (Pls ignore the chinese text in the output. It is not relevant):

    初始化方法 FHT.Tests.Integration.AccountTests.Init 引发异常。MyTested.WebApi.Exceptions.HttpResponseMessageAssertionException:  MyTested.WebApi.Exceptions.HttpResponseMessageAssertionException: 
    When testing ServerHttpMessageHandler expected HTTP response message result status code to be 200 (OK), but instead received 400 (BadRequest).。

        在 MyTested.WebApi.Builders.HttpMessages.HttpHandlerResponseMessageTestBuilder.ThrowNewHttpResponseMessageAssertionException(String propertyName, String expectedValue, String actualValue)
       在 MyTested.WebApi.Utilities.Validators.HttpResponseMessageValidator.WithStatusCode(HttpResponseMessage httpResponseMessage, HttpStatusCode statusCode, Action`3 failedValidationAction)
       在 MyTested.WebApi.Builders.HttpMessages.HttpHandlerResponseMessageTestBuilder.WithStatusCode(HttpStatusCode statusCode)
       在 FHT.Tests.Integration.AccountTests.YuanJianSignInToGetToken(String currentPassword) 位置 e:\FHT\FHT\FHT.Tests\Integration\AccountTests.cs:行号 40
       在 FHT.Tests.Integration.AccountTests.Init() 位置 e:\FHT\FHT\FHT.Tests\Integration\AccountTests.cs:行号 35

The only information I get is that the actual status code is 400, not 200, which is correct but not helpful. 

Remember, if I send this request via curl or postman, I could read the actual HTTP body that says that the password is wrong, like this:

    {
      "error": "invalid_grant",
      "error_description": "The user name or password is incorrect."
    }

I wrote a simple alternative as an extension method:

    public static class MyTestedWebApiExtensions
    {
        public static IHttpHandlerResponseMessageTestBuilder WithStatusCodeOrElseDumpResponseContent(this IHttpHandlerResponseMessageTestBuilder builder, HttpStatusCode statusCode)
        {
            try
            {
                builder.WithStatusCode(statusCode);
            }
            catch
            {
                var message = builder.AndProvideTheHttpResponseMessage();
                var content = message.Content.ReadAsStringAsync().Result;
                throw new Exception(content);
            }

            return builder;
        }
    }

which when replacing `WithStatusCode`, gives me the following exception message instead:

    初始化方法 FHT.Tests.Integration.AccountTests.Init 引发异常。System.Exception:  
    System.Exception: {"error":"invalid_grant","error_description":"The user name or password is incorrect."}。

        在 FHT.Tests.Integration.MyTestedWebApiExtensions.WithStatusCodeOrElseDumpResponseContent(IHttpHandlerResponseMessageTestBuilder builder, HttpStatusCode statusCode) 位置 e:\FHT\FHT\FHT.Tests\Integration\AccountTests.cs:行号 172
       在 FHT.Tests.Integration.AccountTests.YuanJianSignInToGetToken(String currentPassword) 位置 e:\FHT\FHT\FHT.Tests\Integration\AccountTests.cs:行号 40
       在 FHT.Tests.Integration.AccountTests.Init() 位置 e:\FHT\FHT\FHT.Tests\Integration\AccountTests.cs:行号 35

Including the Http body in the exception is more intuitive when debugging as there might be thousand causes for 400.

**Comment by foresightyj** [comment]
make title more appropriate.

**Comment by ivaylokenov** [comment]
@foresightyj You are refering to integration tests, correct? I like the feature, it will be better to debugging. I believe it can be on a more global level - the HTTP information can be retrieved in case of any unsuccessful status code and appended to the exception message. For example in the following class: [HttpHandlerResponseMessageTestBuilder](https://github.com/ivaylokenov/MyTested.WebApi/blob/c024b9fece4e96ba570d2fba111c90b1a5ddb739/src/MyTested.WebApi/Builders/HttpMessages/HttpHandlerResponseMessageTestBuilder.cs) the method `ThrowNewHttpResponseMessageAssertionException` can append the HTTP response information - status code, content, headers, etc. This way it will be available on every failed test.
For unit testing scenarios, I believe it will not be possible, since the `HttpResponseMessage` is not resolved during the test.

Otherwise, this is a perfect way to suggest features - if you want the feature as soon as possible, you can open a pull request, otherwise I will add it in the next couple of days.

**Comment by foresightyj** [comment]
Ah yes. It is in the integration test. Your suggestion is better. I'd really like to view everything in the response, just like what I can see in Postman.

**Comment by ivaylokenov** [comment]
@foresightyj Implemented in version 1.2.1. You can update the package. HTTP response details now are shown in the exception message.
